server:
  port: 8888 # 端口号

spring:
  datasource:
    url: jdbc:h2:~/mydb  # 数据库
    driver-class-name: org.h2.Driver
    username: root
    password: test
  h2:
    console:
      path: /h2-console  #h2嵌入式数据库控制台，可以通过浏览器访问
      enabled: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启sql日志
    map-underscore-to-case: true # 开启驼峰映射(mp默认开启)
