server:
  port: 9900
spring:
  application:
    name: user-service
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/userservicedb
    username: postgres
    password: 123456
    druid:
      connect-timeout: 180000
  flyway:
    enabled: true
    encoding: UTF-8
    locations: classpath:db/migration
    validate-on-migrate: true