#server:
#  port: 9000
#spring:
#  application:
#    name: gateway
#  profiles:
#    active: dev
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/gatewaydb
#    username: postgres
#    password: 123456
#    druid:
#      connect-timeout: 180000
